### PR TITLE
Feature/#386 mileage in charge table

### PR DESCRIPTION
**Pull request by stevoh6**
Feature for this idea: #386.

Tested with my car, it works fine.

### CODE REVIEW

**Comment by flobz** [comment]
thanks a lot for your contribution ! :)

**Comment by flobz** [comment]
@stevoh6 I did a review, can you answer me please ?

**Comment by stevoh6** [comment]
hi yes what and where is the question? i dont see it on mobile :)

**Comment by flobz** [comment]
@stevoh6 https://github.com/flobz/psa_car_controller/pull/462/files#diff-9f1db3566cd98cf3bee0d7b45f86d4a3c61941a9f30e9ca6d1d14313f737befbL79-R87 here

**Review by stevoh6 — COMMENTED** [review]
Review,  I dont see any breaking changes or comments.

**Review by stevoh6 — COMMENTED** [review]
.

**Comment by stevoh6** [comment]
> @stevoh6 https://github.com/flobz/psa_car_controller/pull/462/files#diff-9f1db3566cd98cf3bee0d7b45f86d4a3c61941a9f30e9ca6d1d14313f737befbL79-R87 here

Unfortunately, I obviously cannot see your comments :/

**Comment by stevoh6** [comment]
@flobz Could you please check it, why I cannot see them?

**Pull request merged**
