### PR TITLE
Update car_models.yml

### PR DESCRIPTION
**Pull request by BenAChilds**
Adds 508 SW II

### CODE REVIEW

**Comment by flobz** [comment]
thanks ! :)

**Comment by Zwordi** [comment]
Hi,

Based on your recent merge and v3.
I don’t see my merge anymore. Did you choose to get rid of the non-electric cars ?

Thanks,

**Comment by flobz** [comment]
I don't understand it's in master branch : https://github.com/flobz/psa_car_controller/blob/master/psa_car_controller/psacc/resources/car_models.yml 
_Did you choose to get rid of the non-electric cars ?_
No

**Comment by Zwordi** [comment]
Hi,

Yes it is but not in your most recent release ans the rework you did :).

Sorry my question was a bit out of the blue.

I was expexting for a New release and a new Docker image to go further  with my tests.

Thanks


13 avr. 2022 23:02:45 Florian BEZANNIER ***@***.***>:

**Comment by Zwordi** [comment]
Hi @flobz,

Sorry to bother you but I couldn’t find my entry on your lastest release so I think something happen on the car_models files during your rework.

May I push a new merge request ?

Thanks,

**Pull request merged**
