### PR TITLE
fix ApiException 400

### LINKED ISSUE #674: 400 - server_error : Internal Server Error
Car: Vauxhall Corsa E

When I attempt to authenticate under 'My Car Details' I get the error message: 400 - server_error : Internal Server Error

Attempted on: Windows 10 PC and HomeAssistant running on a Raspberry Pi 4

I have used this tool for years, but this error has just emerged. I have attempted on older versions and newer versions but the issue is recurring.

### LINKED ISSUE #678: 400 Error: PSA status API seems to have changed?
### 400 HTTP Error when requesting vehicle status 
_as of (23/11/23)_

**To Reproduce**
simply start program and if required call local endpoint http://localhost:5000/get_vehicleinfo/<VIN> to provoke status API call to PSA, or wait until program does it by itself...

Log output to console shows this: ( I have enabled HTTP debugging in urllib3 in addition to your application debugging, so you can see exactly what happens on the wire). 
**_Note the 400 response payload indicates something to do with a Header error. (in bold below):_**

2023-11-24 09:50:08,107 DEBUG Starting new HTTPS connection (1): api.groupe-psa.com:443
2023-11-24 09:50:08,107 :: DEBUG :: Starting new HTTPS connection (1): api.groupe-psa.com:443
send: b'GET /connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e/status?extension=odometer&client_id=122f3511-4f74-4a0c-bcda-af2f3b2e3a65 HTTP/1.1\r\nHost: api.groupe-psa.com\r\nAccept-Encoding: identity\r\nAccept: application/hal+json\r\nUser-Agent: Swagger-Codegen/4.0/python\r\nAuthorization: Bearer _<********removed*********>_\r\nx-introspect-realm: clientsB2CVauxhall\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Connection: close
header: Date: Fri, 24 Nov 2023 09:50:07 GMT
header: Expires: 0
header: Cache-Control: no-store, no-cache, must-revalidate, private
header: Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 23-Nov-2023 09:50:07 GMT
header: Set-Cookie: JSESSIONID=Kv440m8cC1gwo0yaUoqbH1Q9ASwE7e0aTAOAfVhc; path=/
header: Strict-Transport-Security: max-age=15724800; includeSubDomains
header: Content-Type: application/hal+json
header: X-Global-Transaction-ID: 32486679656071cfda9a6a3f
header: User-Agent: Swagger-Codegen/4.0/python
header: Set-Cookie: PSACountry=GB; Domain=.groupe-psa.com; Path=/
2023-11-24 09:50:08,796 DEBUG https://api.groupe-psa.com:443 "GET /connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e/status?extension=odometer&client_id=122f3511-4f74-4a0c-bcda-af2f3b2e3a65 HTTP/1.1" 400 None
2023-11-24 09:50:08,796 :: DEBUG :: https://api.groupe-psa.com:443 "GET /connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e/status?extension=odometer&client_id=122f3511-4f74-4a0c-bcda-af2f3b2e3a65 HTTP/1.1" 400 None
**2023-11-24 09:50:08,808 :: DEBUG :: response body: {"uuid":"35bb70e9-ff95-412a-bb7a-bbd287523323","code":40000,"message":" Invalid parameter: X-MPHSource","timestamp":"2023-11-24T09:50:07.941Z"}**
2023-11-24 09:50:08,810 :: ERROR :: get_vehicle_info: ApiException: (400)
Reason: Bad Request

**Environment (please complete the following information):**
 - OS: Windows
 - Brand and model of car: Vauxhall Corsa-e
 - Application version (commit number, branch or tag): PSACC 3.0.12

**Possible Solution**
**_Problem is resolved by removing [extension=odometer] query string property._** 

I have tested [with curl] the same API call without this parameter; it works successfully and odometer object appears to still be included in the response:

curl -v -k --header "Authorization: Bearer <*****removed*****>" --header "Host: api.groupe-psa.com" --header "x-introspect-realm: clientsB2CVauxhall" --header "Content-Type: application/json" --header "Accept: application/hal+json" --header "Accept-Encoding: identity" --get "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e/status?client_id=122f3511-4f74-4a0c-bcda-af2f3b2e3a65"
< HTTP/1.1 200 OK
< Connection: close
< Date: Fri, 24 Nov 2023 10:11:50 GMT
< Expires: 0
< Cache-Control: no-store, no-cache, must-revalidate, private
< Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 23-Nov-2023 10:11:50 GMT
< Set-Cookie: JSESSIONID=h7Yjbi8bexWqtQzc2j6zXF_b9twnqnWCq452p__T; path=/
< Strict-Transport-Security: max-age=15724800; includeSubDomains
< Content-Type: application/hal+json
< X-Global-Transaction-ID: 08f333a5656076e60298c23f
< User-Agent: curl/7.54.0
< Set-Cookie: PSACountry=GB; Domain=.groupe-psa.com; Path=/
<
(formatted for readability)
{
	"createdAt": "2023-11-24T09:44:47Z",
	"updatedAt": "2023-11-24T09:44:47Z",
	"ignition": {
		"createdAt": "2023-11-24T09:44:47Z",
		"type": "Stop"
	},
	"battery": {
		"voltage": 71.5,
		"createdAt": "2023-11-24T09:44:47Z"
	},
	"privacy": {
		"createdAt": "2023-11-24T09:44:47Z",
		"state": "None"
	},
	"service": {
		"createdAt": "2023-10-20T19:43:00Z",
		"type": "Electric"
	},
	"environment": {
		"luminosity": {
			"createdAt": "2023-11-24T09:44:47Z",
			"day": true
		},
		"air": {
			"createdAt": "2023-11-24T09:44:47Z",
			"temp": 8.5
		}
	},
	**"odometer": {
		"createdAt": "2023-11-24T09:44:47Z",
		"mileage": 6218.1
	},**
	"_links": {
		"self": {
			"href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e/status?profile=endUser"
		},
		"vehicle": {
			"href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/1c8bedfe1bd229d9cf0fee6613462af127a77c0a3ca67b4cad3399856d40cad6f7e13d53f4930922a8159da20f738a579e576284871a4ddb840f3d72016cfad9248617be0f502e8de8b47c0ef511388e72acafd3bd348b2f0220e2956f14fe25e"
		}
	},
	"preconditioning": {
		"airConditioning": {
			"createdAt": "2023-11-24T09:44:47Z",
			"updatedAt": "2023-11-24T09:44:47Z",
			"status": "Disabled",
			"programs": [
				{
					"enabled": false,
					"slot": 1,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 2,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 3,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 4,
					"recurrence": "Daily",
					"start": "PT0S"
				}
			]
		}
	},
	"energies": [
		{
			"createdAt": "2023-11-24T09:44:47Z",
			"type": "Electric",
			"subType": "ElectricEnergy",
			"level": 76,
			"autonomy": 260,
			"extension": {
				"electric": {
					"battery": {
						"load": {
							"createdAt": "2023-11-24T09:44:47Z",
							"capacity": 36640,
							"residual": 26304
						}
					},
					"charging": {
						"plugged": false,
						"status": "Disconnected",
						"chargingRate": 0,
						"chargingMode": "No",
						"nextDelayedTime": "PT30M"
					}
				}
			}
		}
	],
	"preconditionning": {
		"airConditioning": {
			"createdAt": "2023-11-24T09:44:47Z",
			"updatedAt": "2023-11-24T09:44:47Z",
			"status": "Disabled",
			"programs": [
				{
					"enabled": false,
					"slot": 1,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 2,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 3,
					"recurrence": "Daily",
					"start": "PT0S"
				},
				{
					"enabled": false,
					"slot": 4,
					"recurrence": "Daily",
					"start": "PT0S"
				}
			]
		}
	},
	"energy": [
		{
			"createdAt": "2023-11-24T09:44:47Z",
			"updatedAt": "2023-11-24T09:44:47Z",
			"type": "Electric",
			"level": 76,
			"autonomy": 260,
			"charging": {
				"plugged": false,
				"status": "Disconnected",
				"chargingRate": 0,
				"chargingMode": "No",
				"nextDelayedTime": "PT30M"
			}
		}
	]
}

### PR DESCRIPTION
**Pull request by mdkeil**
thxs to @slash909uk
fix #678

### CODE REVIEW

**Comment by Apollon77** [comment]
I also verified this fix

**Comment by sod75** [comment]
I can Also confirm this fixed the issue for me

**Comment by wjansenw** [comment]
I manually adjusted the above directly in the docker container, and it works! Tnx!

**Comment by Reddax** [comment]
Also manually adjusted the above and now works correctly

**Comment by unixtall** [comment]
> I manually adjusted the above directly in the docker container, and it works! Tnx!

how did you do it? i cant find the file

**Comment by flobz** [comment]
Thanks for the fix

**Pull request merged**
