### PR TITLE
Use correct realm and oauth url based on users input

### PR DESCRIPTION
**Pull request by Maxus1998**
https://github.com/flobz/psa_car_controller/issues/4

### CODE REVIEW

**Comment by flobz** [comment]
Sorry I correct the code before seeing your pull request.

**Comment by flobz** [comment]
tanks for 14e4501 though

**Comment by Maxus1998** [comment]
I updated the PR.
You can still merge it for automatic detection of the package name if you want

The other stuff are only format chanegs by my IDE (pyCharm) as far as I am aware

**Comment by flobz** [comment]
I apply 14e4501 and  9265bb5.
Thanks to you it should works with all PSA vehicles.

**Pull request closed without merging**
