### PR TITLE
added mail and password to cmd arguments

### PR DESCRIPTION
**Pull request by Mrgove10**
This make it much easier to start it from command line in case you need to do it multiple times.

### CODE REVIEW

**Comment by flobz** [comment]
Thanks for the PR.
Is there a reason to precise a default value for the two args?

**Comment by Mrgove10** [comment]
No actualy that is an error on my part, they should not be any defaults, sorry

**Comment by flobz** [comment]
can you fix it please ?

**Comment by Mrgove10** [comment]
fixed in https://github.com/flobz/psa_car_controller/pull/7

**Pull request closed without merging**
