### PR TITLE
Update car_models.yml

### PR DESCRIPTION
**Pull request by rchiileea**
added peugeot 308 sw hybrid

Just added this car and correct items with vin, hope it does not get deleted

### CODE REVIEW

**Comment by flobz** [comment]
Your other PR weren't not closed by me. If it was the message would have been "closed by flobz". The branch "patch-2" doesn't exist anymore so it's might be the cause of the issue.

**Comment by rchiileea** [comment]
> Your other PR weren't not closed by me. If it was the message would have been "closed by flobz". The branch "patch-2" doesn't exist anymore so it's might be the cause of the issue.

hoping this works, did you see the icons I added (to custom brand icons) all psa group brands are availible now

**Comment by flobz** [comment]
thanks for your contribution

**Comment by flobz** [comment]
no I didn't see the icons.

**Comment by rchiileea** [comment]
https://github.com/elax46/custom-brand-icons

**Pull request merged**
