### PR TITLE
first step to manage hybrid cars

### PR DESCRIPTION
**Pull request by jlayec**

### CODE REVIEW

**Comment by flobz** [comment]
Thanks for your help, thanks to you we can make the app compatible with hybrid car ! hat 
What do you think about create a function to get the electric motor info instead of having the same code in several places ?

``` python
def get_electric_info():
 for energy in data.energy:
    if energy.type == 'Electric':
            return data.energy
    return None
```

**Comment by jlayec** [comment]
Better implementation proposed improving the Energy class and various fixes.

**Comment by flobz** [comment]
I will merge your PR to the master branch when I would have finish to review it. Thanks a lot for your help.

**Comment by jlayec** [comment]
thanks.
if  you want, you can wait before merge to master, I will PR in this feature branch 2 things ready :
- an updated trip algorithm
- an updated dashboard
still have to do
- way to store car parameters (today fuel and battery capacity are static in code)

**Pull request merged**
