### PR TITLE
config.ini accessible from home assistant

### PR DESCRIPTION
**Pull request by pika28**
Hello,

From what I understand, I don't have access to the config.ini file when HA is supervised. Would it be possible to be able to modify the variables in the config.ini file from the addon configuration in home assistant?

Also, the command http://localhost:5000/wakeup/YOURVIN does not work on my end.

Thanks

### CODE REVIEW

**Comment by duanra08** [comment]
Hello pika28,
You find the solution for the HA addon in this discussion:
[https://github.com/flobz/psacc-ha/issues/21](https://github.com/flobz/psacc-ha/issues/21)

**Comment by pika28** [comment]
Hello,

I can't install the addon mentioned in your link. : "SSH & Web Terminal". 

Is it possible to do the same with provided by HAOS?

If I understood correctly, with HAOS supervised, the addons are docker containers? You have to extract the files, modify them, then send them. Is all this done on the command line or with software like WinSCP?

Thanks for your help.

**Comment by duanra08** [comment]
Pika,
the good command is:
`docker exec -it "Names or Container ID" /bin/bash`
After that, you can navigate in the container folders

**Comment by duanra08** [comment]
have you restart the container?

**Comment by pika28** [comment]
yes the container and HAOS

**Comment by duanra08** [comment]
what parameter did you want to change?

**Pull request closed without merging**
