### PR TITLE
Remote control features

### PR DESCRIPTION
**Pull request by papageigit**
The same additions as the previous pull request, but now without changing RemoteClient.py :)

I did not get around to testing the horn (did not want to wake up the neighbors), please someone else test it and advise if the count actually works. I have heard that it only horns three times regardless of set count but cannot verify this.

The lights do work, but they always flash for 10 seconds, regardless of set duration in PSACC. Maybe there is a way to remove the duration field in views.py (so no editing of RemoteClient.py)? I have tried it but ended up with no results.

Lock and unlocking doors also work. They work just like preconditioning the car. So 1 to lock and 0 to unlock.

Added the above to the readme and also cleaned that file up a bit.

### CODE REVIEW

**Comment by Mikado8231** [comment]
What is your car model ?

On my side, I try to test with my Peugeot e208 but it is not eligible

**Comment by papageigit** [comment]
e-2008. Do you have the required services activated? (Used to be called "Remote Control" but I believe this is now part of "Connect Plus")

**Comment by papageigit** [comment]
Please also post the error here so it can be included in the FAQ if necessary.

**Comment by Mikado8231** [comment]
OK, I've not this option.
I'm only with an old service to have a minimum actions (charge and preconditioning)
https://services-store.peugeot.fr/store/e-commandes-distance-0

I can't help you to tests these new features :'(

**Comment by flobz** [comment]
thanks lgtm !

**Pull request merged**
